import { ArrowRight, Banknote, CircleAlert, ClipboardCheck, Target } from 'lucide-react';
import { Link } from 'react-router-dom';
import { Bar, BarChart, CartesianGrid, Cell, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { formatCLP, formatCLPShort } from '@/lib/utils';

export function DemoFinancialStory({cash,receivables,payables,lowest,overdue}:{cash:number;receivables:number;payables:number;lowest:number;overdue:number}){
 const data=[{name:'Caja hoy',value:cash,color:'#10b981'},{name:'Por cobrar',value:receivables,color:'#8b5cf6'},{name:'Por pagar',value:payables,color:'#f59e0b'},{name:'Punto mínimo',value:lowest,color:lowest<0?'#f43f5e':'#14b8a6'}];
 const chapters=[
  {k:'01',title:'La posición',text:`La empresa parte con ${formatCLP(cash)} disponibles.`,icon:Banknote,to:'#financial-kpis',cta:'Entender la caja'},
  {k:'02',title:'La tensión',text:`Hay ${formatCLP(receivables)} por cobrar y ${overdue} vencimiento${overdue===1?'':'s'} atrasado${overdue===1?'':'s'}.`,icon:CircleAlert,to:'#collections',cta:'Priorizar cobros'},
  {k:'03',title:'La decisión',text:`Los compromisos pendientes suman ${formatCLP(payables)}; el orden de pago importa.`,icon:Target,to:'/alerts',cta:'Ver prioridades'},
  {k:'04',title:'El resultado',text:`El punto mínimo proyectado es ${formatCLP(lowest)}. El cierre convierte señales en acciones.`,icon:ClipboardCheck,to:'/weekly-close',cta:'Cerrar la semana'},
 ];
 return <section aria-labelledby="demo-story-title" className="mb-8 overflow-hidden rounded-3xl border border-primary/25 bg-gradient-to-br from-primary/10 via-card to-card shadow-sm">
  <div className="grid gap-6 p-5 sm:p-7 lg:grid-cols-[.85fr_1.15fr]">
   <div><p className="text-sm font-semibold text-primary">Historia financiera · Comercial Andes</p><h1 id="demo-story-title" className="mt-2 max-w-xl font-display text-3xl font-bold tracking-tight sm:text-4xl">La caja no solo se observa. Se convierte en una decisión.</h1><p className="mt-3 max-w-2xl leading-7 text-muted-foreground">Recorre el caso como lo viviría un dueño de PyME: detectar la presión, ordenar la semana y comprobar el resultado.</p><div className="mt-5 inline-flex items-center gap-2 rounded-full border border-primary/25 bg-background/80 px-3 py-1.5 text-xs font-semibold text-primary"><span className="size-2 rounded-full bg-primary"/>Sandbox editable · datos ficticios</div></div>
   <div className="min-h-72 rounded-2xl border border-border bg-background/80 p-4"><div className="flex items-start justify-between gap-3"><div><h2 className="font-semibold">Mapa de la presión de caja</h2><p className="text-xs text-muted-foreground">Comparación de magnitudes, no suma contable</p></div><span className="text-xs font-semibold text-muted-foreground">CLP</span></div><div className="mt-4 h-52" role="img" aria-label="Gráfico de barras con caja actual, cuentas por cobrar, cuentas por pagar y saldo mínimo proyectado"><ResponsiveContainer width="100%" height="100%"><BarChart data={data} margin={{top:8,right:8,left:0,bottom:0}}><CartesianGrid vertical={false} stroke="currentColor" opacity={.1}/><XAxis dataKey="name" tick={{fontSize:11}} interval={0}/><YAxis tickFormatter={v=>formatCLPShort(Number(v))} tick={{fontSize:11}} width={55}/><Tooltip formatter={v=>[formatCLP(Number(v)),'Monto']} contentStyle={{borderRadius:12,fontSize:12}}/><Bar dataKey="value" radius={[8,8,0,0]}>{data.map(item=><Cell key={item.name} fill={item.color}/>)}</Bar></BarChart></ResponsiveContainer></div></div>
  </div>
  <ol className="grid border-t border-border bg-background/55 md:grid-cols-2 lg:grid-cols-4">{chapters.map(({k,title,text,icon:Icon,to,cta})=><li key={k} className="border-border p-5 md:border-r last:border-r-0"><div className="flex items-center justify-between"><span className="text-xs font-bold tracking-widest text-primary">CAPÍTULO {k}</span><Icon className="size-5 text-primary" aria-hidden="true"/></div><h2 className="mt-3 font-semibold">{title}</h2><p className="mt-1 min-h-12 text-sm leading-6 text-muted-foreground">{text}</p><Link to={to} className="mt-3 inline-flex min-h-11 cursor-pointer items-center gap-2 text-sm font-semibold text-primary focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary/60">{cta}<ArrowRight className="size-4"/></Link></li>)}</ol>
  <details className="border-t border-border px-5 py-3 text-sm"><summary className="min-h-11 cursor-pointer py-3 font-semibold">Ver cifras como tabla accesible</summary><dl className="grid gap-3 pb-4 sm:grid-cols-4">{data.map(item=><div key={item.name}><dt className="text-xs text-muted-foreground">{item.name}</dt><dd className="font-semibold">{formatCLP(item.value)}</dd></div>)}</dl></details>
 </section>
}
