-- DEN-127.1: lectura multiusuario real; escrituras existentes permanecen owner-only.
drop policy if exists denarius_tenant_member_select on cashflow.tenant;
create policy denarius_tenant_member_select on cashflow.tenant for select to authenticated using(owner_id=auth.uid()or cashflow.denarius_has_permission(id,'financial.read'));

do $$declare t text;begin foreach t in array array['bank_account','invoice','recurring_transaction','unit_economics_input','weekly_financial_close','msp_task','msp_task_activity','saas_customer','saas_plan','saas_subscription','saas_mrr_event']loop
 if to_regclass('cashflow.'||t)is not null then execute format('drop policy if exists denarius_member_read on cashflow.%I',t);execute format('create policy denarius_member_read on cashflow.%I for select to authenticated using(cashflow.denarius_has_permission(tenant_id,''financial.read''))',t);end if;end loop;end$$;
drop policy if exists denarius_member_read on cashflow.transaction;
create policy denarius_member_read on cashflow.transaction for select to authenticated using(exists(select 1 from cashflow.bank_account a where a.id=account_id and cashflow.denarius_has_permission(a.tenant_id,'financial.read')));

create or replace function cashflow.list_denarius_tenants()returns setof cashflow.tenant language sql security definer stable set search_path=cashflow,public,pg_temp as $$select t from cashflow.tenant t where t.owner_id=auth.uid()or cashflow.denarius_has_permission(t.id,'financial.read')order by t.created_at,t.id$$;
create or replace function cashflow.get_active_denarius_tenant()returns cashflow.tenant language plpgsql security definer set search_path=cashflow,public,pg_temp as $$declare v_uid uuid:=auth.uid();v_tenant cashflow.tenant;begin if v_uid is null then raise exception'AUTH_REQUIRED';end if;select t.*into v_tenant from cashflow.denarius_user_preference p join cashflow.tenant t on t.id=p.active_tenant_id where p.owner_id=v_uid and(t.owner_id=v_uid or cashflow.denarius_has_permission(t.id,'financial.read'));if v_tenant.id is null then select t.*into v_tenant from cashflow.tenant t where t.owner_id=v_uid or cashflow.denarius_has_permission(t.id,'financial.read')order by t.created_at,t.id limit 1;if v_tenant.id is not null then insert into cashflow.denarius_user_preference(owner_id,active_tenant_id)values(v_uid,v_tenant.id)on conflict(owner_id)do update set active_tenant_id=excluded.active_tenant_id,updated_at=now();end if;end if;return v_tenant;end$$;
create or replace function cashflow.set_active_denarius_tenant(p_tenant_id uuid)returns cashflow.tenant language plpgsql security definer set search_path=cashflow,public,pg_temp as $$declare v_uid uuid:=auth.uid();v_tenant cashflow.tenant;begin if v_uid is null then raise exception'AUTH_REQUIRED';end if;select*into v_tenant from cashflow.tenant where id=p_tenant_id and(owner_id=v_uid or cashflow.denarius_has_permission(id,'financial.read'));if v_tenant.id is null then raise exception'TENANT_NOT_ACCESSIBLE';end if;insert into cashflow.denarius_user_preference(owner_id,active_tenant_id)values(v_uid,p_tenant_id)on conflict(owner_id)do update set active_tenant_id=excluded.active_tenant_id,updated_at=now();return v_tenant;end$$;
create or replace function cashflow.denarius_access_context(p_tenant_id uuid)returns jsonb language plpgsql stable security definer set search_path=cashflow,public,pg_temp as $$declare v_tenant cashflow.tenant;v_role text;v_permissions text[];v_platform boolean:=coalesce(auth.jwt()->'app_metadata'->>'denarius_role','')='platform_admin';begin select*into v_tenant from cashflow.tenant where id=p_tenant_id and(owner_id=auth.uid()or cashflow.denarius_has_permission(id,'financial.read'));if v_tenant.id is null then raise exception'tenant_not_found';end if;if v_tenant.owner_id=auth.uid()then v_role:='owner';v_permissions:=array['financial.read','financial.write','close.manage','team.manage','mcp.manage'];else select m.role_key,r.permissions into v_role,v_permissions from cashflow.denarius_tenant_member m join cashflow.denarius_role_template r on r.key=m.role_key where m.tenant_id=p_tenant_id and m.user_id=auth.uid()and m.status='ACTIVE';end if;return jsonb_build_object('business_model',v_tenant.business_model,'can_change_business_model',v_platform or v_role='owner','role',case when v_platform then'platform_admin'else v_role end,'permissions',coalesce(v_permissions,'{}'),'read_only',not('financial.write'=any(coalesce(v_permissions,'{}'))));end$$;
revoke all on function cashflow.list_denarius_tenants(),cashflow.get_active_denarius_tenant(),cashflow.set_active_denarius_tenant(uuid),cashflow.denarius_access_context(uuid)from public,anon;grant execute on function cashflow.list_denarius_tenants(),cashflow.get_active_denarius_tenant(),cashflow.set_active_denarius_tenant(uuid),cashflow.denarius_access_context(uuid)to authenticated;
