-- DEN-109: frescura y cobertura derivadas de escrituras reales.
create or replace function cashflow.data_freshness_workspace(p_tenant_id uuid,p_as_of date default current_date)
returns jsonb language plpgsql stable security invoker set search_path=cashflow,public as $$
declare v_uid uuid:=auth.uid();v_model text;v_sources jsonb;v_overall text;v_required int;v_ready int;
begin
 select business_model into v_model from cashflow.tenant where id=p_tenant_id and owner_id=v_uid;if v_model is null then raise exception'tenant_not_found';end if;
 with raw(source,label,last_updated,row_count,required,deep_link)as(
  select'CASH','Caja y movimientos',greatest((select max(updated_at)from cashflow.bank_account where tenant_id=p_tenant_id and owner_id=v_uid),(select max(t.updated_at)from cashflow.transaction t join cashflow.bank_account a on a.id=t.account_id where a.tenant_id=p_tenant_id and t.owner_id=v_uid)),(select count(*)from cashflow.bank_account where tenant_id=p_tenant_id and owner_id=v_uid),true,'/operations#transactions'
  union all select'INVOICES','Facturas',max(updated_at),count(*),v_model='pyme-tradicional','/operations#invoices' from cashflow.invoice where tenant_id=p_tenant_id and owner_id=v_uid
  union all select'RECURRING','Recurrencias',max(updated_at),count(*),false,'/operations#recurring' from cashflow.recurring_transaction where tenant_id=p_tenant_id and owner_id=v_uid
  union all select'OPERATING_RECORDS','Ingresos y gastos',max(u),sum(n),v_model='pyme-tradicional','/operations' from(select max(updated_at)u,count(*)n from cashflow.expense where tenant_id=p_tenant_id and owner_id=v_uid union all select max(updated_at),count(*)from cashflow.revenue where tenant_id=p_tenant_id and owner_id=v_uid)x
  union all select'UNIT_ECONOMICS','Supuestos unitarios',max(updated_at),count(*),true,'/weekly-close' from cashflow.unit_economics_input where tenant_id=p_tenant_id and owner_id=v_uid and period=date_trunc('month',p_as_of)::date
  union all select'SAAS_LIFECYCLE','Suscripciones y MRR',max(u),sum(n),v_model='startup-saas','/subscriptions' from(select max(created_at)u,count(*)n from cashflow.saas_subscription where tenant_id=p_tenant_id and owner_id=v_uid union all select max(created_at),count(*)from cashflow.saas_mrr_event where tenant_id=p_tenant_id and owner_id=v_uid)x
 ),scored as(select *,case when row_count=0 or last_updated is null then'EMPTY'when p_as_of-last_updated::date<=7 then'FRESH'when p_as_of-last_updated::date<=30 then'AGING'else'STALE'end status,case when last_updated is null then null else p_as_of-last_updated::date end age_days from raw)
 select jsonb_agg(jsonb_build_object('source',source,'label',label,'last_updated',last_updated,'row_count',row_count,'required',required,'deep_link',deep_link,'age_days',age_days,'status',status,'message',case status when'EMPTY'then'Sin datos'when'FRESH'then'Datos actualizados'when'AGING'then'Conviene actualizar esta fuente'else'Datos desactualizados'end)order by required desc,source),count(*)filter(where required),count(*)filter(where required and status in('FRESH','AGING')) into v_sources,v_required,v_ready from scored;
 select case when exists(select 1 from jsonb_array_elements(v_sources)s where(s->>'required')::boolean and s->>'status'='EMPTY')then'INCOMPLETE'when exists(select 1 from jsonb_array_elements(v_sources)s where(s->>'required')::boolean and s->>'status'='STALE')then'STALE'when exists(select 1 from jsonb_array_elements(v_sources)s where(s->>'required')::boolean and s->>'status'='AGING')then'AGING'else'FRESH'end into v_overall;
 return jsonb_build_object('as_of',p_as_of,'business_model',v_model,'overall_status',v_overall,'required_ready',v_ready,'required_total',v_required,'sources',coalesce(v_sources,'[]'));
end $$;

create or replace function cashflow.weekly_close_workspace(p_tenant_id uuid,p_as_of date default current_date)
returns jsonb language plpgsql stable security invoker set search_path=cashflow,public as $$ declare v_uid uuid:=auth.uid();v_core jsonb;v_alerts jsonb;v_unit jsonb;v_fresh jsonb;v_history jsonb;begin
 if not exists(select 1 from cashflow.tenant where id=p_tenant_id and owner_id=v_uid)then raise exception'tenant_not_found';end if;v_core:=cashflow.financial_core_metrics(p_tenant_id,p_as_of);v_alerts:=cashflow.financial_alert_center(p_tenant_id,p_as_of);v_unit:=cashflow.unit_economics(p_tenant_id,to_char(p_as_of,'YYYY-MM'));v_fresh:=cashflow.data_freshness_workspace(p_tenant_id,p_as_of);
 select coalesce(jsonb_agg(jsonb_build_object('id',id,'week_start',week_start,'as_of',as_of,'status',status,'snapshot',snapshot,'note',note,'closed_at',closed_at)order by week_start desc),'[]')into v_history from(select*from cashflow.weekly_financial_close where tenant_id=p_tenant_id and owner_id=v_uid order by week_start desc limit 12)h;
 return jsonb_build_object('week_start',date_trunc('week',p_as_of)::date,'as_of',p_as_of,'core',v_core,'alerts',v_alerts,'unit_economics',v_unit,'freshness',v_fresh,'checklist',jsonb_build_array(jsonb_build_object('id','data','label','Revisar caja y burn','done',true),jsonb_build_object('id','freshness','label','Actualizar fuentes obligatorias','done',v_fresh->>'overall_status' in('FRESH','AGING')),jsonb_build_object('id','alerts','label','Revisar alertas críticas','done',coalesce((v_alerts#>>'{summary,critical}')::int,0)=0),jsonb_build_object('id','economics','label','Completar unit economics','done',v_unit->>'assessment'<>'INCOMPLETE')),'history',v_history);end $$;
revoke all on function cashflow.data_freshness_workspace(uuid,date)from public,anon;grant execute on function cashflow.data_freshness_workspace(uuid,date)to authenticated;
